### ISSUE TITLE
The compiler failed.

### ISSUE THREAD

**Issue by Dayvison** [oscar-broman/ppg#4]
When i click in LST, ASM or Macros give me error `Error: The compiler failed. (3)`.
When i click run, compile and give output all right.

Ubuntu 14.04.3 LTS
Node version: 4.4.5

**Comment by jaysegh** [comment]
Same issue here, running on Debian 8.

**Comment by Dayvison** [comment]
Ok need that. https://github.com/oscar-broman/pawn/blob/master/source/compiler/sc1.c#L1064-L1067
